name = "domain-monitor"
main = "src/index.js"
compatibility_date = "2025-11-17"
keep_vars = true

[[d1_databases]]
binding = "DB"
database_name = "domain-monitor-db"
database_id = "56ef27f7-6783-4a52-9a7a-7ee9154e8351"

